# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Ubuntu 20.04 (Focal Fossa)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:12.0
        env:
          POSTGRES_USER: libreplan
          POSTGRES_PASSWORD: libreplan
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Create libreplandev database
      uses: akanieski/setup-postgres-cli@v0.1.2
      with:
        commands: PGPASSWORD=libreplan psql -U libreplan -h postgres -p 5432 -c "CREATE DATABASE libreplandev;"

    - name: Create libreplandevtest database
      uses: akanieski/setup-postgres-cli@v0.1.2
      with:
        commands: PGPASSWORD=libreplan psql -U libreplan -h postgres -p 5432 -c "CREATE DATABASE libreplandevtest;"

    - name: Set up Maven for nektos act
      uses: stCarolas/setup-maven@v4.4

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -Ddefault.passwordsControl=false -Ddefault.exampleUsersDisabled=false clean install
